### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by dac2020** [berkinet/sr-201-relay#1]
Hi, 

Got a couple of these from amazon and not finding much info then came across your site.
I created the python file but when I run it, I get;

`Traceback (most recent call last):
  File "/home/leena/code/sr-201", line 458, in <module>
    main()
  File "/home/leena/code/sr-201", line 445, in main
    sr_201 = Sr201(argv[i])
  File "/home/leena/code/sr-201", line 200, in __init__
    self.open()
  File "/home/leena/code/sr-201", line 219, in open
    self._soc = socket.create_connection((self._hostname, port))
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
`
Is this because I have to configure something within the script? The device is at default 192.168.1.100 IP.

**Comment by berkinet** [comment]
Hmmm.  First, I seem to recall the script was written for Python2.7. Are you running it in 3?   Can you send me the entire script and I’ll look at it tomorrow.

**Comment by dac2020** [comment]
Yes, I'm running it on manjaro which has 3.10 installed. I can try it on another system that might have something lower.
The script is identical to yours, just a copy.

**Comment by dac2020** [comment]
Gives the same or similar error using python 2.7.

**Comment by berkinet** [comment]
Did you create an action group with appropriate arguments as described in this indigo forum post?

https://forums.indigodomo.com/viewtopic.php?f=118&t=19004&p=154132&hilit=sr+201+relay#p145096

**Comment by dac2020** [comment]
No, there is mention of that in the thread but no information that I can see at least on what needs to be done.
Not a python person :)

I would be happy simply communicating with it from the command line, just can't find any info on how to send it tcp commands.
There are some hints at doing just that inside the script but I'm missing what ever the initiating program/method is to send commands.

**Comment by dac2020** [comment]
I got the python script working now.
Have to find more info on how to communicate with it using simple tcp commands.
 Thanks very much.

**Comment by dac2020** [comment]
For anyone looking like I did...

<pre>
#        0R     No operation (but return status).
#        1R*    Close relay if it's open, wait approx 1/2 a second, open relay.
#        1R     Close relay if it's open.
#        1R:0   Close relay if it's open.
#        1R:n   Close relay if it's open, then in n seconds (1 <= n <= 65535) open it.
#        2R     Open relay if it's closed.
#
#    Where:
#        R      is the relay number, '1' .. '8'.  The main board has relay's '1' and '2', the extension board (if present) has the rest.
#               If R is 'X' all relays are effected.
#
#    If the command is sent over TCP (not UDP, TCP only), the relay will reply with a string of 8 0's and 1's, representing the "before" command
#    was executed" state of relay's 1..8 in that order.  A '0' is sent if the relay is open, '1' if closed.
#
# THE DEVICE: TCP Configuration
#    Commands are ASCII strings that must be sent in one TCP packet.  'i' is a random number in the range '1000' .. '9999':
#
#    #1i;       Query State.  Response is a comma separated list of fields terminated by a semicolon (';').  Example response:
#
#                 >192.168.1.100,255.255.255.0,192.168.1.1,,0,435,F44900F6087457000000,192.168.1.1,connect.tutxxx.com,0;
#
#               Fields in order of appearance are:
#
#               ID  Value in example     Description
#               --  -------------------- ---------------------------------
#                2  192.168.1.100        Devices IP Address.
#                3  255.255.255.0        Devices subnet mask.
#                4  192.168.1.1          Gateway.
#                5                       Unknown.
#                6  0                    '1'=Save relay state across poweroff.
#                7  435                  Software version is 1.0.435 / reset.
#               na  F44900F6087457000000 Device serial number.
#                8  192.168.1.1          DNS Server to look up cloud service.
#                9  connect.tutxxx.com   Cloud service.
#                A  0                    Cloud service enabled if = '1'.
#
#    #Di,F;    Set the state whose ID is 'D' to value 'F'.  For example:
#
#                #61234,1;      Persist relay state across power cycle.
#                #71234;        Reset the device so changes take effect.

### Change IP from default 192.168.1.100 ###

# ./sr-201-relay.py 192.168.1.100 gateway=0.0.0.0
# ./sr-201-relay.py 192.168.1.100 dns=0.0.0.0
# ./sr-201-relay.py 192.168.1.100 ip=192.168.1.41
# ./sr-201-relay.py 192.168.1.100 reset

# ./sr-201-relay.py 192.168.1.41 close:1
# ./sr-201-relay.py 192.168.1.41 close:0
# ./sr-201-relay.py 192.168.1.41 open:1
# ./sr-201-relay.py 192.168.1.41 open:2

### Get config ###
# ./sr-201-relay.py 192.168.1.41 config
</pre>
